### ISSUE TITLE
Zebra stripes

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#100]
```css
.zebra tr:nth-child(odd) { background: #fff; }
.zebra tr:nth-child(even) { background: #edf3f5; }
.zebra tr:only-child,
.zebra tr:nth-last-child(2):first-child, 
.zebra tr:nth-last-child(2):first-child ~ tr { background: none; }
```

This will ignore the table if only two rows.
