### ISSUE TITLE
tidy

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#101]
```css
.tidy > :first-child { margin-top: 0 !important; }
.tidy > :last-child { margin-bottom: 0 !important; }
```
