### ISSUE TITLE
Flexbox full screen layout

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#105]
```css
*,
*::before,
*::after { box-sizing: border-box; }

html { height: 100%; }
body { min-height: 100%; }

html,
body { overflow-x: hidden; }
html { overflow-y: auto; }

/*--------------------------------------------------------------------*/

[eta-line],
[eta-stacked] { display: flex; }

[eta-line],
[eta-stacked] { flex-direction: column; }

[eta-line] > [eta-primary],
[eta-stacked] > [eta-primary] { flex: 1 0 auto; }

[eta-secondary],
[eta-tertiary] { flex: 0 0 auto; }

@media (min-width: 48rem) {
	[eta-line] { flex-direction: row; }
	[eta-line] > [eta-primary] { flex: 0 1 auto; }
	[eta-line] > [eta-secondary] {
		flex-basis: 20%;
		max-width: 20rem;
		min-width: 10rem;
	}
	[eta-line] > [eta-tertiary] {
		flex-basis: 15%;
		max-width: 20rem;
		min-width: 10rem;
	}
}

/*--------------------------------------------------------------------*/

[eta-primary],
[eta-secondary],
[eta-tertiary] {
	padding-right: 2rem;
	padding-left: 2rem;
}
[eta-line],
[eta-stacked] { padding: 0; }
```

```html
<!doctype html>
<html lang=en>
<head>
	<meta charset=utf-8>
	<title></title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css">
	<link rel="stylesheet" href="../assets/styles/latest.css">
	<style>
		div { box-shadow: inset 0 0 1px #000; }
	</style>
</head>
<body eta-stacked>
	
	<div eta-secondary>
		<p>Lorem ipsum dolor sit amet</p>
	</div>
	
	<div eta-primary eta-line>
		
		<div eta-secondary>
			<p>Lorem ipsum dolor sit amet</p>
		</div>
		
		<div eta-primary eta-line>
			
			<div eta-primary>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.</p>
				<p>Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien.</p>
				<p>Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut eros et nisl sagittis vestibulum. Nullam nulla eros, ultricies sit amet, nonummy id, imperdiet feugiat, pede.</p>
				<p>Sed lectus. Donec mollis hendrerit risus. Phasellus nec sem in justo pellentesque facilisis. Etiam imperdiet imperdiet orci. Nunc nec neque. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi. Curabitur ligula sapien, tincidunt non, euismod vitae, posuere imperdiet, leo. Maecenas malesuada. Praesent congue erat at massa. Sed cursus turpis vitae tortor. Donec posuere vulputate arcu. Phasellus accumsan cursus velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue, elit erat euismod orci, ac placerat dolor lectus quis orci. Phasellus consectetuer vestibulum elit. Aenean tellus metus, bibendum sed, posuere ac, mattis non, nunc. Vestibulum fringilla pede sit amet augue. In turpis. Pellentesque posuere. Praesent turpis. Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus. Donec elit libero, sodales nec, volutpat a, suscipit non, turpis. Nullam sagittis. Suspendisse pulvinar, augue ac venenatis condimentum, sem libero volutpat nibh, nec pellentesque velit pede quis nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce id purus. Ut varius tincidunt libero. Phasellus dolor. Maecenas vestibulum mollis</p>
			</div>
			
			<div eta-tertiary>
				<p>Lorem ipsum dolor sit amet</p>
			</div>
			
		</div>
		
		<div eta-tertiary>
			<p>Lorem ipsum dolor sit amet</p>
		</div>
		
	</div>
	
	<div eta-tertiary>
		<p>Lorem ipsum dolor sit amet</p>
	</div>
	
</body>
</html>
```

![](https://cloud.githubusercontent.com/assets/218624/21826468/7196f2c2-d73c-11e6-8911-45dbd785663e.png)
