### ISSUE TITLE
Funky ass animated link hover underline shit

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#110]
```css
a,
a:visited {
	color: #0f0077;
	text-decoration: none;
}
a:visited:hover,
a:focus,
a:focus:hover,
a:hover,
a:active {
	color: #d68100;
	text-decoration: none;
}
a.selected {
	box-shadow: inset 0 -2px 0 #0f0077;
	-webkit-transition: box-shadow 100ms linear;
	-moz-transition: box-shadow 100ms linear;
	-ms-transition: box-shadow 100ms linear;
	-o-transition: box-shadow 100ms linear;
	transition: box-shadow 100ms linear;
}
a.selected:visited:hover,
a.selected:focus,
a.selected:focus:hover,
a.selected:hover,
a.selected:active { box-shadow: none; }
```
