### ISSUE TITLE
 min-height: 100vh; alternative to 100% min-height on body and html

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#111]

**Comment by mhulse** [comment]
```css
html { height: 100%; }
body {
	min-height: 100%;
	min-height: 100vh;
}
```

Is fallback.
