### ISSUE TITLE
Another flexbox layout (login landing page)

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#119]
```css
*,
*::before,
*::after {
    -webkit-box-sizing: border-box;
     -khtml-box-sizing: border-box;
       -moz-box-sizing: border-box;
        -ms-box-sizing: border-box;
         -o-box-sizing: border-box;
            box-sizing: border-box;
}

html { height: 100%; }
body { min-height: 100%; }

html,
body { overflow-x: hidden; }
html { overflow-y: auto; }

body {
    display: flex;
    flex-direction: column;
}

/*--------------------------------------------------------------------*/

#container {
    flex: 1 0 auto;
    display: flex;
    flex-direction: column;
}

#top,
#bottom {
    flex: 0 0 auto;
}

#middle {
    flex: 1 0 auto;
}

#top,
#bottom {
    padding: 20px;
}

#middle {
    padding: 30px 20px;
}

/*--------------------------------------------------------------------*/

#middle {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
}

#wrapper {
    max-width: 990px;
    flex: 1;
    display: flex;
    flex-direction: column;
}

#primary,
#secondary,
#tertiary {
    padding: 20px;
}

@media (min-width: 480px) {

    #wrapper {
        flex-direction: row;
        flex: 1;
    }

    #primary {
        flex: 1;
        margin: -20px 0;
    }

    #secondary {
        flex: 0 0 15%;
    }

    #tertiary {
        flex: 0 0 15%;
        order: -1;
    }

}

/*--------------------------------------------------------------------*/
/* Layout Skin */

html,
body { background: #000; }

#container {
    background: linear-gradient(to bottom, #91c0ba, #477b85);
}

#top {
    text-align: right;
    color: #000;
}

#bottom {
    color: #fff;
}

.box {
    box-shadow: 0 3px 5px 0 rgba(59, 84, 89, .5);
}

#primary {
    color: #fff;
    background: #05282e;
    border: 2px solid #031417;
    border-radius: 5px;
    position: relative;
    z-index: 100;
}

#secondary {
    border-radius: 0 5px 5px 0;
    background: #fff;
}

#tertiary {
    border-radius: 5px 0 0 5px;
    background: hsla(39, 11%, 74%, 1);
}
```

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>xxx</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <link rel="stylesheet" href="assets/plugins/normalize.css/normalize.css">
    <link rel="stylesheet" href="assets/styles/login.css">

</head>
<body>

<div id="container">

    <header id="top">

        Top

    </header>

    <main id="middle">

        <div id="wrapper">

            <div id="primary">

                primary primary primary

            </div>

            <div id="secondary">

                secondary secondary secondary

            </div>

            <div id="tertiary">

                tertiary tertiary tertiary

            </div>

        </div>

    </main>

    <footer id="bottom">

        Bottom

    </footer>

</div>

</body>
</html>
```

![fireshot capture 13 - xxx - http___bit local_ieq_uc-denver-split-theme_login html](https://cloud.githubusercontent.com/assets/218624/26030800/4e85589a-3813-11e7-825c-78a113e33037.png)

![fireshot capture 12 - xxx - http___bit local_ieq_uc-denver-split-theme_login html](https://cloud.githubusercontent.com/assets/218624/26030799/4e8385d8-3813-11e7-81fd-694f31146254.png)
