### ISSUE TITLE
Cool Button

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#124]
```html
<div class="info">
    <div class="btn">
        <a href="#info" class="button-push">
        <span class="inner info-btn"><img src="img/info-icon.svg" type="image/svg+xml" alt="Info"><span>Info</span></span></a>
    </div>
</div>
```

```css
.btn {
    padding: 10px 0 0 20px;
    margin: -10px 0 0 10px;
    overflow: hidden
}
.button-push, .button-push .inner {
    display: inline-block;
    border-radius: .2em
}
.button-push {
    position: relative;
    background-color: #131313;
    margin-top: 20px;
    margin-bottom: 30px
}
.button-push .info-btn {
    background-color: #fff;
    color: #131313
}
.button-push .inner:after, .button-push .inner:before {
    width: 10px;
    height: 10px;
    background: #131313;
    position: absolute;
    content: ""
}

.button-push .inner {
    border: 10px solid #131313;
    padding: 4px 12px 0 16px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    -webkit-transform: translate3d(-.325em, -.325em, 0);
    transform: translate3d(-.425em, -.425em, 0);
    -webkit-transition: -webkit-transform 240ms cubic-bezier(.175, .885, .32, 1.275);
    -o-transition: transform 240ms cubic-bezier(.175, .885, .32, 1.275);
    transition: transform 240ms cubic-bezier(.175, .885, .32, 1.275);
    transition: transform 240ms cubic-bezier(.175, .885, .32, 1.275), -webkit-transform 240ms cubic-bezier(.175, .885, .32, 1.275);
    -webkit-transition-delay: 0s;
    -o-transition-delay: 0s;
    transition-delay: 0s
}

.button-push .inner:before {
    display: block;
    left: 100%;
    margin-left: 9px;
    top: -8px;
    -webkit-transform: skewY(45deg);
    -ms-transform: skewY(45deg);
    transform: skewY(45deg);
    -webkit-transform-origin: top left;
    -ms-transform-origin: top left;
    transform-origin: top left;
    -webkit-transition: width 240ms cubic-bezier(.175, .885, .32, 1.275), -webkit-transform 240ms cubic-bezier(.175, .885, .32, 1.275);
    transition: width 240ms cubic-bezier(.175, .885, .32, 1.275), -webkit-transform 240ms cubic-bezier(.175, .885, .32, 1.275);
    -webkit-transition-delay: 0s;
    -o-transition-delay: 0s;
    transition-delay: 0s
}

.button-push .inner:after {
    display: block;
    top: 100%;
    left: -8px;
    margin-top: 9px;
    -webkit-transform: skewX(45deg);
    -ms-transform: skewX(45deg);
    transform: skewX(45deg);
    -webkit-transform-origin: top left;
    -ms-transform-origin: top left;
    transform-origin: top left;
    -webkit-transition: height 240ms cubic-bezier(.175, .885, .32, 1.275), -webkit-transform 240ms cubic-bezier(.175, .885, .32, 1.275);
    transition: height 240ms cubic-bezier(.175, .885, .32, 1.275), -webkit-transform 240ms cubic-bezier(.175, .885, .32, 1.275)
}

.button-push:hover .inner:before {
    width: 0
}

.button-push:hover .inner:after {
    height: 0
}

.button-push.click .inner, .button-push:hover .inner {
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
    -webkit-transition: -webkit-transform 120ms cubic-bezier(.23, 1, .32, 1);
    -o-transition: transform 120ms cubic-bezier(.23, 1, .32, 1);
    transition: transform 120ms cubic-bezier(.23, 1, .32, 1);
    transition: transform 120ms cubic-bezier(.23, 1, .32, 1), -webkit-transform 120ms cubic-bezier(.23, 1, .32, 1)
}

#info, #info a.close {
    bottom: 0;
    -webkit-transition: opacity .2s;
    right: 0
}

.button-push .inner img {
    padding-right: 12px;
    margin-bottom: -5px;
    object-fill: contain
}

a.button-push {
    float: right
}
```
