### ISSUE TITLE
Bootstrap3 showing/hiding utils

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#125]
```css
// Classes
.show {
  display: block !important;
}
.hidden {
  display: none !important;
}
.invisible {
  visibility: hidden;
}
```

Simple, but I always forget what names are. The above seem good (on top of what I already use).
