### ISSUE TITLE
Gradient text

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#126]
```css
.dl-highlights h2 {
	background: linear-gradient(to right, cyan, violet);
	background-clip: text;
	-webkit-background-clip: text;
	-webkit-text-fill-color: transparent;
	font-size: 2.2em;
	margin-top: 0;
	position: relative
}

.dl-highlights h2::before {
	content: ' ';
	width: 60%;
	height: 2px;
	background-color: #444;
	position: absolute;
	bottom: -15px;
	left: 50%;
	-webkit-transform: translateX(-50%);
	transform: translateX(-50%)
}
```

```html
<h2>Free &amp; Open Source</h2>
```

<img width="275" alt="screenshot 2017-08-17 22 04 56" src="https://user-images.githubusercontent.com/218624/29444907-20381e7a-8398-11e7-958e-ec393d91f519.png">
