### ISSUE TITLE
Disable clicks and make look inactive

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#127]
```css
.disabled {
    pointer-events: none;
    cursor: default;
    opacity: 0.6;
}
```
