### ISSUE TITLE
Kill

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#128]
```css
.kill > :first-child {
    margin-top: 0 !important;
}
.kill > :last-child {
    margin-bottom: 0 !important;
}
```
