### ISSUE TITLE
Highlight outline text with no shift

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#129]
```css
.highlight {
	-webkit-box-shadow: inset 0 0 0 5px #ffad08 !important;
	-moz-box-shadow: inset 0 0 0 5px #ffad08 !important;
	box-shadow: inset 0 0 0 5px #ffad08 !important;
	z-index: 1000;
}
```

and another example:

```css
.audio-playing {
	-webkit-box-shadow: 0 0 5px 1px #0c8f8f;
	-moz-box-shadow: 0 0 5px 1px #0c8f8f;
	box-shadow: 0 0 5px 1px #0c8f8f;
	-webkit-border-radius: 3px;
	-moz-border-radius: 3px;
	border-radius: 3px
}
```
