### ISSUE TITLE
Justified left CSS text

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#130]
```css
p {
	text-align: justify;
	text-align-last: left;
	-webkit-hyphens: auto;
	-moz-hyphens: auto;
    hyphens: auto;
}
````
