### ISSUE TITLE
Background video

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#131]
How to use HTML5 Background Videos in your website
In order to use background videos, you'd ideally supply them in 3 versions. Those are MP4, OGV and WEBM. OGV is not really necessary though, unless you want to support the old Browsers Firefox 3.5 & 3.6, Opera 10.5 and Chrome 3, 4, & 5.

You would be using a HTML5 video tag like so

```html
<video autoplay loop muted poster="media/image/road.jpg" id="background">
   <source src="media/video/road.mp4" type="video/mp4">
   <source src="media/video/road.webm" type="video/webm">
   <source src="media/video/road.ogv" type="video/ogg">
</video>
```

The above code also sets a poster. That is shown while the video loads or in browsers that can't play the video. To create a video poster, you could play the video on your computer, pause it and use shift + command + 4 (MAC. On Windows you could use the standard Snipping Tool.

And then you\d format this with CSS:

```css
#background {
   display:none;
   position: fixed;
   top: 50%;
   left: 50%;
   min-width: 100%;
   min-height: 100%;
   width: auto;
   height: auto;
   z-index: -100;
   -webkit-transform: translateX(-50% translateY(-50%;
   transform: translateX(-50% translateY(-50%;
}	
```

But we show that background video only on larger devices. Because on mobile phones background video may take up too many system resources. So we add this media query (replace the min-width: 62em with a value from your own css framework if you like

```css
@media (min-width: 62em {
   #background {
      display:block;
   } 
}
```

http://converterpoint.com/
