### ISSUE TITLE
Full page body and html

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#138]
```css
html { height: 100%; }
body { min-height: 100%; }
```

**Comment by mhulse** [comment]
Note that in Safari, `height: 100%` can cause issues with printing and page breaks:

```html
...
first page
...
<div class="print-break"></div>
...
second page
...
```

```css
@media print {
    html {
        height: auto;
    }
    .print-break {
        display: block;
        page-break-before: always;
        position: relative;
    }
}
```
