### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#140]
```css
a,
a:visited {
	color: red;
	text-decoration: none;
}
a:visited:hover,
a:focus,
a:focus:hover,
a:hover,
a:active {
	color: blue;
	text-decoration: underline;
}
```
