### ISSUE TITLE
Hide semantically “untitled” empty headings

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#141]
Don’t display the title if none given (semantically “untitled”, h/t [camen design](http://camendesign.com/)):

```css
h1:empty { display: none; }
```
