### ISSUE TITLE
Box model

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#143]
```css
*,
*::before,
*::after {
    -webkit-box-sizing: border-box;
    -khtml-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    -o-box-sizing: border-box;
    box-sizing: border-box;
}
```
