### ISSUE TITLE
Clearing floats

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#144]
```css
.clear::after {
    content: "";
    display: table;
    clear: both;
}
```

Older version:

```css
.fix {
    *zoom: 1;
}
.fix::before,
.fix::after {
    content: " ";
    display: table;
}
.fix::after {
    clear: both;
}
```
