### ISSUE TITLE
Hide an element

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#145]
Remove completely, non-SEO or accessible-friendly:

```css
.gone {
	display: none !important;
	visibility: hidden;
}
```

Hide, but retain SEO and accessible friendliness:

```css
.off {
	border: 0;
	clip: rect(0 0 0 0);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute;
	width: 1px;
}
```

Hide visually, but retain space:

```css
.ghost { visibility: hidden; }
```
