### ISSUE TITLE
Remove link outline

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#146]
```css
.nix,
.nix:focus,
.nix:hover,
.nix:active {
	color: rgba(0, 0, 0, 0);
	text-decoration: none;
	outline: 0;
	border: 0;
}
```
