### ISSUE TITLE
Fix margin collapse

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#147]
```css
.force {
	margin-top: -1px;
	margin-bottom: -1px;
	padding: 1px 0;
}
```
