### ISSUE TITLE
Stop words from breaking out of containers

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#148]
```css
.nono {
	word-wrap: break-word;
	overflow-wrap: break-word;
	/*
	-ms-word-break: break-all;
	    word-break: break-all;
	    word-break: break-word;
	*/
}
```
