### ISSUE TITLE
Responsive scrolling box

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#149]
Simple solution for responsive thingys (like `<table>`s):

```css
/*
@see http://www.maxdesign.com.au/2013/03/22/simple-responsive-table/
@see http://creativeandcode.com/simple-solution-for-responsive-tables/
@see http://stackoverflow.com/a/10122689/922323
*/

/*
<div class="scroll"><img ...></div>
<div class="scroll"><table></table></div>
*/

.scroll {
	width: 100%;
	overflow-y: auto;
	-webkit-overflow-scrolling: touch;
}
.scroll img:first-of-type {
	max-width: none;
	/*display: block;*/
}
.scroll > *,
.scroll img:first-of-type {
	margin-top: 0;
	margin-bottom: 0;
	-webkit-transform: translateZ(0);
}
```
