### ISSUE TITLE
Simple two-column float, fixed left sidebar

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#153]
```css
/*
Simple two-column:
<div class="box">
	<(any element)>
	<(any element)>
</div>
*/

@media (min-width: 737px) {
	.box::after {
		content: "";
		display: table;
		clear: both;
	}
	.box > :first-child {
		width: 300px;
		float: left;
		display: inline;
	}
	.box > :last-child { margin-left: 340px; }
}
```
