### ISSUE TITLE
Text on left, middle and right, same line

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#157]
```css
/*
<div class="split">
	<div>left</div>
	<div>middle</div>
	<div>right</div>
</div>
*/

.split::after {
	content: "";
	display: table;
	clear: both;
}
.split { position: relative; }
.split > div {
	text-align: center;
	width: 100%;
	position: absolute;
	z-index: 1;
}
.split > div:first-child,
.split > div:last-child {
	width: auto;
	position: relative;
	z-index: 2;
}
.split > div:first-child {
	text-align: left;
	float: left;
}
.split > div:last-child {
	text-align: right;
	float: right;
}
```
