### ISSUE TITLE
Exact color printing

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#162]
```css
/* http://stackoverflow.com/a/15253634/922323 */
*,
*:before,
*:after { -webkit-print-color-adjust: exact; }
```
