### ISSUE TITLE
Grayscale printing

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#163]
```css
[container="print"] * {
    -webkit-filter: grayscale(100%);
       -moz-filter: grayscale(100%);
        -ms-filter: grayscale(100%);
         -o-filter: grayscale(100%);
            filter: grayscale(100%);
}
```
