### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#167]
```css
img {
	border: 0;
	max-width: 100%;
	height: auto;
	vertical-align: top;
}
```

Disable responsive images:

```css
.none { max-width: none; }
```
