### ISSUE TITLE
More media stuffs

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#17]
```css
img {
	
	border: 0;
	max-width: 100%;
	height: auto;
	vertical-align: top;
	
	a & {
		border: 0;
		outline: 0;
	}
	
}

iframe { border: 0; }

iframe,
object,
embed {
	max-width: 100%;
	outline: 0;
}

audio,
video {
	
	vertical-align: middle;
	display: block;
	
	&:focus,
	&:active { outline: 0; }
	
}

audio {
	width: 100%;
	margin: 20px 0;
}
```
