### ISSUE TITLE
Image captions

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#170]
Images inline with copy (width of container based on image’s inherent width):

```css
/*
<figure class="fig">
	<img src="http://www.placehold.it/150x150">
	<figcaption class="figcap">
		<p>This is the caption.</p>
	</figcaption>
</figure>
 */

.fig {
	margin: 0 auto;
	display: table;
}
.fig img {
	display: block;
	width: 100%;
}
.fig .figcap {
	display: table-caption;
	caption-side: bottom;
}
```

Same as above, but using hard-coded width (allows for image to be as big as desired, which can be good for retina displays):

```css
/*
<figure class="media">
	<img src="foo.jpg">
	<figcaption>
		<p>This is the caption.</p>
	</figcaption>
</figure>
*/

.media { width: 150px; }
.media img {
	max-width: 100%;
	display: block;
	margin: 0 auto;
}
.media-right {
	margin: 0 0 20px 20px;
	float: right;
	display: inline;
}
.media-left {
	margin: 0 20px 20px 0;
	float: left;
	display: inline;
}
```
