### ISSUE TITLE
Simple flexbox column layout with margins inbetween

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#18]
Would be nice to have for quick and dirty copy/paste.

**Comment by mhulse** [comment]
Here's a holy grail layut:

http://www.cssplay.co.uk/layouts/cssplay-flex-basic-layout.html

```css
/*
<div ft-grid="wrap">
	<div ft-grid="top"> … </div>
	<div ft-grid="row">
		<div ft-grid="primary"> … </div>
		<div ft-grid="secondary"> … </div>
		<div ft-grid="tertiary"> … </div>
	</div>
	<div ft-grid="bottom"> … </div>
</div>
*/

[ft-grid="wrap"] {
	display: -webkit-flex;
	display: -khtml-flex;
	display: -moz-flex;
	display: -ms-flex;
	display: -o-flex;
	display: flex;
	-webkit-flex-direction: column;
	 -khtml-flex-direction: column;
	   -moz-flex-direction: column;
	    -ms-flex-direction: column;
 	     -o-flex-direction: column;
	        flex-direction: column;
}
[ft-grid="top"] {
	-webkit-flex: 0 0 100px;
	 -khtml-flex: 0 0 100px;
	   -moz-flex: 0 0 100px;
	    -ms-flex: 0 0 100px;
	     -o-flex: 0 0 100px;
	        flex: 0 0 100px;
}
[ft-grid="row"] {
	display: -webkit-flex;
	display: -khtml-flex;
	display: -moz-flex;
	display: -ms-flex;
	display: -o-flex;
	display: flex;
	-webkit-flex: 1 0 auto;
	 -khtml-flex: 1 0 auto;
	   -moz-flex: 1 0 auto;
	    -ms-flex: 1 0 auto;
	     -o-flex: 1 0 auto;
	        flex: 1 0 auto;
	-webkit-flex-direction: row;
	 -khtml-flex-direction: row;
	   -moz-flex-direction: row;
	    -ms-flex-direction: row;
 	     -o-flex-direction: row;
	        flex-direction: row;
}
[ft-grid="primary"] {
	-webkit-flex: 1;
	 -khtml-flex: 1;
	   -moz-flex: 1;
	    -ms-flex: 1;
	     -o-flex: 1;
	        flex: 1;
}
[ft-grid="secondary"] {
	-webkit-flex: 0 0 200px;
	 -khtml-flex: 0 0 200px;
	   -moz-flex: 0 0 200px;
	    -ms-flex: 0 0 200px;
	     -o-flex: 0 0 200px;
	        flex: 0 0 200px;
	order: -1;
}
[ft-grid="tertiary"] {
	-webkit-flex: 0 0 200px;
	 -khtml-flex: 0 0 200px;
	   -moz-flex: 0 0 200px;
	    -ms-flex: 0 0 200px;
	     -o-flex: 0 0 200px;
	flex: 0 0 200px;
}

[ft-grid="bottom"] {
	-webkit-flex: 0 0 100px;
	 -khtml-flex: 0 0 100px;
	   -moz-flex: 0 0 100px;
	    -ms-flex: 0 0 100px;
 	     -o-flex: 0 0 100px;
	        flex: 0 0 100px;
}
```

**Comment by mhulse** [comment]
```css
#chart-parent {
	display: -webkit-box;
	display: -webkit-flex;
	display: -moz-box;
	display: -ms-flexbox;
	display: flex;
	-webkit-box-orient: horizontal;
	-webkit-box-direction: normal;
	-webkit-flex-direction: row;
	   -moz-box-orient: horizontal;
	   -moz-box-direction: normal;
	    -ms-flex-direction: row;
	        flex-direction: row;
}
#chart-primary {
	-webkit-box-flex: 1;
	-webkit-flex: 1;
	   -moz-box-flex: 1;
	    -ms-flex: 1;
	        flex: 1;
}
#chart-secondary {
	display: -webkit-box;
	display: -webkit-flex;
	display: -moz-box;
	display: -ms-flexbox;
	display: flex;
	-webkit-box-orient: vertical;
	-webkit-box-direction: normal;
	-webkit-flex-direction: column;
	   -moz-box-orient: vertical;
	   -moz-box-direction: normal;
	    -ms-flex-direction: column;
	        flex-direction: column;
	-webkit-box-align: center;
	-webkit-align-items: center;
	   -moz-box-align: center;
	    -ms-flex-align: center;
	        align-items: center;
	-webkit-justify-content: space-around;
	    -ms-flex-pack: distribute;
	        justify-content: space-around;
}
```

and:

```html
<div id="chart-parent">
	<div id="chart-secondary">
		<p>dddd</p>
		<p>ddddd</p>
		<p>dddddd</p>
	</div>
	<div id="chart-primary">
		<h3>Pattern over time</h3>
		<div id="chart-wrapper">
			<canvas id="chart-canvas" width="400" height="400"></canvas>
		</div>
	</div>
</div>
```
