### ISSUE TITLE
Css circle

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#23]
Easy, but would be nice to have a quick copy/paste.

**Comment by mhulse** [comment]
```css
#dot {
	border-radius: 50%;
	width: 20px;
	height: 20px;
	background: red;
}
```
