### ISSUE TITLE
Top/bottom inset borders

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#27]
```css
nav[role="navigation"] .container {
	box-shadow: 0 -3px 0 red inset, /* Top */
	            0 3px 0 red inset;  /* Bottom */
}
```

Useful if you need child elements to overlap borders.
