### ISSUE TITLE
Animating things on hover

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#28]
```scss
a {
	
	box-shadow: inset 0 -4px 0 $primary;
	
	-webkit-transition: box-shadow 100ms linear;
	   -moz-transition: box-shadow 100ms linear;
	    -ms-transition: box-shadow 100ms linear;
	     -o-transition: box-shadow 100ms linear;
	        transition: box-shadow 100ms linear;
	
	&,
	&:visited {
		color: $raven;
		text-decoration: none;
	}
	.no-touch &:visited:hover,
	&:focus,
	.no-touch &:focus:hover,
	.no-touch &:hover,
	&:active {
		color: $primary;
		box-shadow: none;
	}
	
}
```
