### ISSUE TITLE
.force CSS version

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#30]
Probably good to have pure CSS options too, for quick prototyping:

```css
.force {
	margin-top: -1px;
	margin-bottom: -1px;
	padding: 1px 0;
}
```
