### ISSUE TITLE
images img

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#31]
```css


img {
	border: 0;
	max-width: 100%;
	height: auto;
	vertical-align: top;
}
a img {
	border: 0;
	outline: 0;
}
.imgc {
	margin: 0 auto;
	display: block;
}
.imgr {
	float: right;
	margin-left: 10px;
}
.imgl {
	float: left;
	margin-right: 10px;
}
.imgr,
.imgl { margin-bottom: 10px; }
@media screen and (max-width: 48em) {
	.imgr,
	.imgl {
		float: none;
		display: block;
		margin: 0 auto;
	}
}
```
