### ISSUE TITLE
Neo columns

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#33]
```css
[elements]::after {
	content: "";
	display: table;
	clear: both;
}
[elements] > * {
	width: 27rem;
	float: left;
}
[elements="left"] > :first-child {
	margin-right: 1rem;
}
[elements="left"] > :last-child {
	width: calc(100% - 28rem);
}
[elements="right"] > :first-child {
	width: calc(100% - 28rem);
}
[elements="right"] > :last-child {
	margin-left: 1rem;
}
```

```html
<div elements="left">
<div>Will  be sidebar to left</div>
<div></div>
</div>

<div elements="right">
<div>Will  be sidebar to right</div>
<div></div>
</div>
```
