### ISSUE TITLE
Hero gradient overlay

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#34]
``` css
#slides {
    position: relative;
}
#slides > div {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background: linear-gradient(to top, rgba(40, 67, 76, 1) 0, rgba(45, 76, 86, 0.5) 30%, rgba(53, 90, 102, 0) 75%);
}
```

``` html
<div id="slides">
<div>...</div>
</div>
```
