### ISSUE TITLE
Selection

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#35]
``` scss
::-moz-selection {
    background: rgba($tertiary, .55);
    text-shadow: none;
}

::selection {
    background: rgba($tertiary, .55);
    text-shadow: none;
}
```
