### ISSUE TITLE
Padded SCSS

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#36]
```scss
// <span><span>Some text</span></span>
.padded {
	
	padding: 10px;
	display: inline; /* If not already. */
	background: rgba($brand-info, .9);
	box-decoration-break: clone;
	
	> span { position: relative; } // Prevents background overlap on wrapped lines.
	
}
```
