### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#37]
```scss
%arrow {
	font-family: FontAwesome;
	line-height: 0;
	position: relative;
	font-style: normal;
	font-weight: normal;
	text-decoration: inherit;
	//display: inline-block;
}
```

… and later:

```scss
a::before {
	@extend %arrow;
	content: "\f177\00a0";
}
```
