### ISSUE TITLE
ios callout on click 

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#38]
Disable completely:

```css
* {
	-webkit-tap-highlight-color: rgba(0, 0, 0, 0);
	-webkit-touch-callout: none;
}
```

But probably best to do it on an as-needed basis.
