### ISSUE TITLE
grayscale

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#41]
```css
[container="print"] * {
	-webkit-filter: grayscale(100%);
	   -moz-filter: grayscale(100%);
	    -ms-filter: grayscale(100%);
	     -o-filter: grayscale(100%);
	        filter: grayscale(100%);
}
```
