### ISSUE TITLE
Blockquote quotes

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#42]
```css
blockquote::before,
blockquote::after {
	font-family: FontAwesome;
	font-style: normal;
	font-weight: normal;
	font-size: 6rem;
	color: rgba(0, 0, 0, .1);
	line-height: 1;
	position: absolute;
}
blockquote::before {
	top: -2.5rem; /*  Half `blockquote` vertical margin. */
	left: -4rem; /* Same as the `blockquote` horizontal margin. */
	content: "\f10d";
}
blockquote::after { content: "\f10e"; }
```
