### ISSUE TITLE
Animated box shadow

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#47]
```css
.shadow { box-shadow: 0 1px 2px rgba(0, 0, 0, .1); }
.shadow::after {
	content: "";
	opacity: 0;
	box-shadow: 0 5px 15px rgba(0, 0, 0, .3);
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	z-index: -1;
	-webkit-transition: opacity .6s cubic-bezier(.165, .84, .44, 1);
	 -khtml-transition: opacity .6s cubic-bezier(.165, .84, .44, 1);
	   -moz-transition: opacity .6s cubic-bezier(.165, .84, .44, 1);
	    -ms-transition: opacity .6s cubic-bezier(.165, .84, .44, 1);
	     -o-transition: opacity .6s cubic-bezier(.165, .84, .44, 1);
	        transition: opacity .6s cubic-bezier(.165, .84, .44, 1);
}
.shadow:hover::after { opacity: 1; }
```
