### ISSUE TITLE
Viewport and calc

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#48]
http://blog.cloudfour.com/breaking-out-with-viewport-units-and-calc/

```css
html,
body {
  overflow-x: hidden;
}
.u-release {
  margin-left: calc(-50vw + 50%);
  margin-right: calc(-50vw + 50%);
}
```
