### ISSUE TITLE
HTML example for fontawesome

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#51]
This one:

```css
/* http://css-tricks.com/examples/IconFont/ */
[data-icon]:before {
    font-family: FontAwesome;
    font-size: inherit;
    font-style: normal;
    font-weight: normal;
    content: attr(data-icon);
    speak: none;
}
```
