### ISSUE TITLE
Play button image

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#52]
```css
/*
<div class="play"><img src="images/foo.jpg"></div>
*/
.play {
	position: relative;
	cursor: pointer;
	cursor: hand;
}
.play::before,
.play::after {
	-webkit-transition: all 100ms linear;
	 -khtml-transition: all 100ms linear;
	   -moz-transition: all 100ms linear;
	    -ms-transition: all 100ms linear;
	     -o-transition: all 100ms linear;
	        transition: all 100ms linear;
}
.play::before {
	content: "\f04b";
	font-family: FontAwesome;
	font-size: 100px;
	font-style: normal;
	font-weight: normal;
	line-height: 0;
	text-decoration: inherit;
	color: #138d9c;
	opacity: .5;
	position: absolute;
	top: 50%;
	right: 50%;
	z-index: 20;
	-webkit-transform: translate(50%, -50%);
	   -moz-transform: translate(50%, -50%);
	    -ms-transform: translate(50%, -50%);
	     -o-transform: translate(50%, -50%);
	        transform: translate(50%, -50%);
}
.play:hover::before {
	color: #fff;
	opacity: 1;
}
.play::after {
	content: "";
	background: rgba(0, 0, 0, 0);
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	z-index: 10;
}
.play:hover::after { background: rgba(0, 0, 0, .5); }
```
