### ISSUE TITLE
Modal background cover

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#54]
```css
body.modal-open {
	position: fixed;
	width: 100%;
	top:0;
	left: 0;
	height: 100%;
	overflow-y: hidden;
	z-index: 10;
}
.modal {
	background: rgba(0, 0, 0, .75);
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	z-index: 1000;
	cursor: pointer;
	cursor: hand;
	display: none;
}
.modal.modal-open { display: block; }
```

Needs more work/example.
