### ISSUE TITLE
Blockquote style

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#55]
```css
blockquote {
	font-size: 14px;
	margin: 0;
	padding: 0;
	position: relative;
}
blockquote p {
	font-size: inherit;
	line-height: inherit;
	background: #e6e6e6;
	border-radius: 5px;
	margin: 10px 0;
	padding: 10px;
	position: relative;
}
blockquote footer {
	padding-left: 20px;
	font-weight: normal;
	letter-spacing: .05em;
	color: #888;
	position: relative;
}
blockquote footer::before {
	content: "";
	width: 0;
	height: 0;
	border-left: 10px solid transparent;
	border-right: 10px solid transparent;
	border-top: 10px solid #e6e6e6;
	position: absolute;
	left: 3em;
	top: -10px;
}
blockquote footer p { margin: 0; }
blockquote * { max-width: none; }
blockquote > :first-child { margin-top: 0 !important; }
blockquote > :last-child { margin-bottom: 0 !important; }
```

```html
<blockquote>
	<p>“I like the Seeing Each Other exercise because it helps me feel closer to my wife.”</p>
	<footer>Macy Rodriguez <span>/ CEO, Acme Inc.</span></footer>
</blockquote>
```

![screenshot 2016-06-14 14 27 25](https://cloud.githubusercontent.com/assets/218624/16060367/297892fc-323c-11e6-82b5-73a00dd6a7c8.png)

**Comment by mhulse** [comment]
Existing BQ needs top/left for position:

```css

/* Quote: */
blockquote { position: relative; }
blockquote > p { padding-left: 3.5em; }
blockquote::before,
blockquote::after {
	font-family: FontAwesome;
	font-style: normal;
	font-weight: normal;
	font-size: 30px;
	color: rgba(0, 0, 0, .1);
	line-height: 1;
	position: absolute;
	z-index: 2;
}
blockquote::before {
	top: 8px;
	left: 10px;
	content: "\f10d";
}
```
