### ISSUE TITLE
Title or button with line behind it in center

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#56]
```css
.divider {
	text-align: center;
	display: block;
	margin: 10px 0;
	position: relative;
}
.divider span {
	line-height: 1;
	display: inline-block;
	background: #fff;
	padding: 5px 10px;
	border-radius: 3px;
	border: 1px solid rgba(0, 0, 0, .1);
	position: relative;
	z-index: 1;
}
.divider span:focus { outline: none; }
.divider::before {
	content: '';
	background: rgba(0, 0, 0, .2);
	height: 1px;
	width: 100%;
	position: absolute;
	left: 0;
	top: 50%;
	-webkit-transform: translateY(-50%);
	        transform: translateY(-50%);
	z-index: 0;
}
```

```html
<div class="divider">
<span role="button" tabindex="0"><span>Show More</span></span>
</div>
```

Inner span I can hide and use `::after/before` to say "show more" or "show less".
