### ISSUE TITLE
Bootstrap close button

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#59]
From: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css

```css
.close {
	float: right;
	font-size: 21px;
	font-weight: bold;
	line-height: 1;
	color: #000;
	text-shadow: 0 1px 0 #fff;
	filter: alpha(opacity=20);
	opacity: .2;
}
.close:hover,
.close:focus {
	color: #000;
	text-decoration: none;
	cursor: pointer;
	filter: alpha(opacity=50);
	opacity: .5;
}
button.close {
	-webkit-appearance: none;
	padding: 0;
	cursor: pointer;
	background: transparent;
	border: 0;
}
```

```html
<button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
```

**Comment by mhulse** [comment]
Non-bootstrap close button:

```css
[ft-close],
[ft-close]:visited {
	text-decoration: none;
	line-height: 1;
	text-indent: -999em;
	white-space: nowrap;
	width: 38px;
	height: 38px;
	margin: 0;
	padding: 0;
	background: #000 url(../plugins/font-awesome/close.svg) no-repeat center 45%;
	background-size: 60%;
	border-radius: 50%;
	box-shadow: 0 0 5px rgba(0, 0, 0, .5);
	overflow: hidden;
	position: absolute;
	top: -10px;
	right: -10px;
}
[ft-close]:visited:hover,
[ft-close]:focus,
[ft-close]:focus:hover,
[ft-close]:hover,
[ft-close]:active {
	text-decoration: none;
	cursor: pointer;
	background-color: red;
	color: rgba(0, 0, 0, 0);
	text-decoration: none;
	outline: 0;
	border: 0;
}
button[ft-close] {
	-webkit-appearance: none;
	padding: 0;
	cursor: pointer;
	border: 0;
}
```

Using https://github.com/encharm/Font-Awesome-SVG-PNG

**Comment by mhulse** [comment]
Close with FontAwesome in the markup:

```css
.close {
	font-size: 2.5rem;
	line-height: 3rem;
	white-space: nowrap;
	color: #fff;
	width: 3rem;
	height: 3rem;
	margin: 0;
	padding: 0;
	border: 0;
	background: transparent;
	overflow: hidden;
	position: absolute;
	right: 1rem;
	top: 50%;
	transform: translateY(-50%);
	z-index: 999;
	cursor: pointer;
	cursor: hand;
	border: none transparent;
	border: 1px solid red;
	border-radius: 0;
	zoom: 1;
	box-shadow: none;
	-webkit-appearance: none;
	-webkit-tap-highlight-color: transparent;
	-webkit-user-drag: none;
	user-select: none;
}
.close,
.close:visited,
.close:visited:hover,
.close:focus,
.close:focus:hover,
.close:hover,
.close:active {
	/* color: rgba(0, 0, 0, 0); */
	text-decoration: none;
	outline: 0;
	border: 0;
}
```

```html
<button class="close" data-remodal-action="close"><i class="fa fa-times" aria-hidden="true"></i></button>
```
