### ISSUE TITLE
Wtf? Display none?

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#61]
https://github.com/mhulse/css-bullets#layout

``` css
.box > :first-child { display: none; }
```

Why?

Remove.
