### ISSUE TITLE
Pattern overlays

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#66]
```css
.pattern::after {
	content: "";
	background: transparent url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAYAAAAGCAYAAADgzO9IAAAAJElEQVQImWMU7p3znwECGBmQABMDDsCCpBJFJ14dMICiE6cOAMPUBE3H6wOnAAAAAElFTkSuQmCC') center center repeat;
	background-size: 3px 3px;
	position: absolute;
	top: 0;
	left: 0;
	bottom: 0;
	right: 0;
	overflow: hidden;
	opacity: .75;
}
```

![overlay 2x](https://cloud.githubusercontent.com/assets/218624/16474223/b53606aa-3e29-11e6-90b6-3b7175ba1e20.png)
