### ISSUE TITLE
Social icons and shit

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#68]
https://github.com/mhulse/picard/blob/gh-pages/dev/css/picard.css

https://github.com/mhulse/picard/blob/gh-pages/dev/index.html#L923-L975

**Comment by mhulse** [comment]
```css
a.social span {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}
a.social.fa-lg {
  font-size: 1.3875em;
}
a.social, a.social:visited {
  color: #999999;
}
a.social:visited:hover, a.social:focus, a.social:focus:hover, a.social:hover, a.social:active {
  color: #666666;
  text-decoration: none;
}

a.social-twitter, a.social-twitter:visited, a.social-twitter:visited:hover, a.social-twitter:focus, a.social-twitter:focus:hover, a.social-twitter:hover, a.social-twitter:active {
  color: #41b7d8;
}

a.social-facebook, a.social-facebook:visited, a.social-facebook:visited:hover, a.social-facebook:focus, a.social-facebook:focus:hover, a.social-facebook:hover, a.social-facebook:active {
  color: #3b5997;
}

a.social-google-plus, a.social-google-plus:visited, a.social-google-plus:visited:hover, a.social-google-plus:focus, a.social-google-plus:focus:hover, a.social-google-plus:hover, a.social-google-plus:active {
  color: #d64937;
}

a.social-linkedin, a.social-linkedin:visited, a.social-linkedin:visited:hover, a.social-linkedin:focus, a.social-linkedin:focus:hover, a.social-linkedin:hover, a.social-linkedin:active {
  color: #0073b2;
}

a.social-pinterest, a.social-pinterest:visited, a.social-pinterest:visited:hover, a.social-pinterest:focus, a.social-pinterest:focus:hover, a.social-pinterest:hover, a.social-pinterest:active {
  color: #cb2027;
}

a.social-vk, a.social-vk:visited, a.social-vk:visited:hover, a.social-vk:focus, a.social-vk:focus:hover, a.social-vk:hover, a.social-vk:active {
  color: #54769b;
}

a.social-xing, a.social-xing:visited, a.social-xing:visited:hover, a.social-xing:focus, a.social-xing:focus:hover, a.social-xing:hover, a.social-xing:active {
  color: #006567;
}

a.social-tumblr, a.social-tumblr:visited, a.social-tumblr:visited:hover, a.social-tumblr:focus, a.social-tumblr:focus:hover, a.social-tumblr:hover, a.social-tumblr:active {
  color: #34465d;
}
```

```html
<p>
	
	<a title="Tweet this" class="social social-twitter fa-stack fa-lg" href="https://twitter.com/intent/tweet?text=YOUR-TITLE&amp;url=YOUR-URL&amp;via=TWITTER-HANDLE" target="_blank" rel="nofollow">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-twitter fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Tweet this</span>
	</a>
	
	<a title="Share on Facebook" class="social social-facebook fa-stack fa-lg" href="http://www.facebook.com/sharer/sharer.php?u=YOUR-URL" target="_blank" rel="nofollow">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-facebook fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Share on Facebook</span>
	</a>
	
	<a title="Plus on Google+" class="social social-google-plus fa-stack fa-lg" href="https://plus.google.com/share?url=YOUR-URL" target="_blank" rel="nofollow">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-google-plus fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Plus on Google+</span>
	</a>
	
	<a title="" class="social social-linkedin fa-stack fa-lg" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=YOUR-URL&amp;title=YOUR-TITLE&amp;summary=YOUR-SUMMARY&amp;source=YOUR-URL" target="_blank" rel="nofollow">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-linkedin fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Share on LinkedIn</span>
	</a>
	
	<a title="Pin on Pinterest" class="social social-pinterest fa-stack fa-lg" href="http://pinterest.com/pin/create/button/?url=YOUR-URL&amp;description=YOUR-DESCRIPTION&amp;media=YOUR-IMAGE-SRC" target="_blank" rel="nofollow">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-pinterest fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Pin on Pinterest</span>
	</a>
	
	<a title="Share on VK" class="social social-vk fa-stack fa-lg" href="https://vk.com/share.php?url=YOUR-URL&amp;title=YOUR-TITLE&amp;description=YOUR-DESCRIPTION&amp;image=YOUR-IMAGE-SRC&amp;noparse=true" target="_blank" rel="nofollow">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-vk fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Share on VK</span>
	</a>
	
	<a title="Share on Xing" class="social social-xing fa-stack fa-lg" href="https://www.xing-share.com/app/user?op=share;sc_p=xing-share;url=YOUR-URL" target="_blank" rel="nofollow">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-xing fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Share on Xing</span>
	</a>
	
	<a title="Share on Tumblr" class="social social-tumblr fa-stack fa-lg" href="http://www.tumblr.com/share?v=3&amp;u=YOUR-URL&amp;t=YOUR-TITLE" target="_blank" rel="nofollow">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-tumblr fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Share on Tumblr</span>
	</a>
	
	<a title="Send via e-mail" class="social social-email fa-stack fa-lg" href="mailto:EMAIL_RECIPIENT?subject=EMAIL_SUBJECT&amp;body=EMAIL_BODY" target="_blank" rel="nofollow">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-envelope fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Send via e-mail</span>
	</a>
	
	<a title="Leave a comment" class="disqus social social-comment fa-stack fa-lg" href="#comments">
		<i class="fa fa-circle fa-stack-2x" aria-hidden="true"></i><i class="fa fa-comment fa-stack-1x fa-inverse" aria-hidden="true"></i>
		<span class="off">Leave a comment</span>
	</a>
	
</p>
```

And here's a watered down version of the HTML:

```html
	<p>
		<a title="Tweet this" href="https://twitter.com/intent/tweet?text=YOUR-TITLE&amp;url=YOUR-URL&amp;via=TWITTER-HANDLE" target="_blank" rel="nofollow">Tweet this</a>
		<a title="Share on Facebook" href="http://www.facebook.com/sharer/sharer.php?u=YOUR-URL" target="_blank" rel="nofollow">Share on Facebook</a>
		<a title="Plus on Google+" href="https://plus.google.com/share?url=YOUR-URL" target="_blank" rel="nofollow">Plus on Google+</a>
		<a title="Share on LinkedIn" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=YOUR-URL&amp;title=YOUR-TITLE&amp;summary=YOUR-SUMMARY&amp;source=YOUR-URL" target="_blank" rel="nofollow">Share on LinkedIn</a>
		<a title="Pin on Pinterest" href="http://pinterest.com/pin/create/button/?url=YOUR-URL&amp;description=YOUR-DESCRIPTION&amp;media=YOUR-IMAGE-SRC" target="_blank" rel="nofollow">Pin on Pinterest</a>
		<a title="Share on VK" href="https://vk.com/share.php?url=YOUR-URL&amp;title=YOUR-TITLE&amp;description=YOUR-DESCRIPTION&amp;image=YOUR-IMAGE-SRC&amp;noparse=true" target="_blank" rel="nofollow">Share on VK</a>
		<a title="Share on Xing" href="https://www.xing-share.com/app/user?op=share;sc_p=xing-share;url=YOUR-URL" target="_blank" rel="nofollow">Share on Xing</a>
		<a title="Share on Tumblr" href="http://www.tumblr.com/share?v=3&amp;u=YOUR-URL&amp;t=YOUR-TITLE" target="_blank" rel="nofollow">Share on Tumblr</a>
		<a title="Send via e-mail" href="mailto:EMAIL_RECIPIENT?subject=EMAIL_SUBJECT&amp;body=EMAIL_BODY" target="_blank" rel="nofollow">Send via e-mail</a>
	</p>
```

**Comment by mhulse** [comment]
Cleaned up:

```css
a.social span {
	border: 0;
	clip: rect(0 0 0 0);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute;
	width: 1px;
}
a.social.fa-lg { font-size: 1.3875em; }
a.social,
a.social:visited { color: #999; }
a.social:visited:hover,
a.social:focus,
a.social:focus:hover,
a.social:hover,
a.social:active {
	color: #666;
	text-decoration: none;
}
a.social-twitter,
a.social-twitter:visited,
a.social-twitter:visited:hover,
a.social-twitter:focus,
a.social-twitter:focus:hover,
a.social-twitter:hover,
a.social-twitter:active { color: #41b7d8; }
a.social-facebook,
a.social-facebook:visited,
a.social-facebook:visited:hover,
a.social-facebook:focus,
a.social-facebook:focus:hover,
a.social-facebook:hover,
a.social-facebook:active { color: #3b5997; }
a.social-google-plus,
a.social-google-plus:visited,
a.social-google-plus:visited:hover,
a.social-google-plus:focus,
a.social-google-plus:focus:hover,
a.social-google-plus:hover,
a.social-google-plus:active { color: #d64937; }
a.social-linkedin,
a.social-linkedin:visited,
a.social-linkedin:visited:hover,
a.social-linkedin:focus,
a.social-linkedin:focus:hover,
a.social-linkedin:hover,
a.social-linkedin:active { color: #0073b2; }
a.social-pinterest,
a.social-pinterest:visited,
a.social-pinterest:visited:hover,
a.social-pinterest:focus,
a.social-pinterest:focus:hover,
a.social-pinterest:hover,
a.social-pinterest:active { color: #cb2027; }
a.social-vk,
a.social-vk:visited,
a.social-vk:visited:hover,
a.social-vk:focus,
a.social-vk:focus:hover,
a.social-vk:hover,
a.social-vk:active { color: #54769b; }
a.social-xing,
a.social-xing:visited,
a.social-xing:visited:hover,
a.social-xing:focus,
a.social-xing:focus:hover,
a.social-xing:hover,
a.social-xing:active { color: #006567; }
a.social-tumblr,
a.social-tumblr:visited,
a.social-tumblr:visited:hover,
a.social-tumblr:focus,
a.social-tumblr:focus:hover,
a.social-tumblr:hover,
a.social-tumblr:active { color: #34465d; }
```
