### ISSUE TITLE
Callout CSS and html

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#69]
```css
.callout {
	color: #333;
	letter-spacing: .03em;
}
.callout a { font-weight: bold; }
.callout a,
.callout a:visited {
	color: #333;
	text-decoration: none;
}
.callout a:visited:hover,
.callout a:focus,
.callout a:focus:hover,
.callout a:hover,
.callout a:active {
	color: #333;
	text-decoration: underline;
}
.callout.callout-box {
	font-size: 16px;
	line-height: 1.2;
	background-color: #ddd;
	border-width: 1px;
	border-style: solid;
	border-color: #bbb;
	padding: 15px;
	border-radius: 6px;
}
.callout.callout-box.callout-info {
	background-color: #d9edf7;
	border-color: #bce8f1;
}
.callout.callout-box.callout-success {
	background-color: #dff0d8;
	border-color: #d6e9c6;
}
.callout.callout-box.callout-warning {
	background-color: #fcf8e3;
	border-color: #faebcc;
}
.callout.callout-box.callout-danger {
	background-color: #f2dede;
	border-color: #ebccd1;
}
.callout.callout-info { color: #31708f; }
.callout.callout-info a,
.callout.callout-info a:visited,
.callout.callout-info a:visited:hover,
.callout.callout-info a:focus,
.callout.callout-info a:focus:hover,
.callout.callout-info a:hover,
.callout.callout-info a:active { color: #31708f; }
.callout.callout-success { color: #3c763d; }
.callout.callout-success a,
.callout.callout-success a:visited,
.callout.callout-success a:visited:hover,
.callout.callout-success a:focus,
.callout.callout-success a:focus:hover,
.callout.callout-success a:hover,
.callout.callout-success a:active { color: #3c763d; }
.callout.callout-warning { color: #8a6d3b; }
.callout.callout-warning a,
.callout.callout-warning a:visited,
.callout.callout-warning a:visited:hover,
.callout.callout-warning a:focus,
.callout.callout-warning a:focus:hover,
.callout.callout-warning a:hover,
.callout.callout-warning a:active { color: #8a6d3b; }
.callout.callout-danger { color: #a94442; }
.callout.callout-danger a,
.callout.callout-danger a:visited,
.callout.callout-danger a:visited:hover,
.callout.callout-danger a:focus,
.callout.callout-danger a:focus:hover,
.callout.callout-danger a:hover,
.callout.callout-danger a:active { color: #a94442; }
```

```html

<p class="callout" role="alert" aria-live="assertive"><i class="fa fa-question-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>
<p class="callout callout-box" role="alert" aria-live="assertive"><i class="fa fa-question-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>

<p class="callout callout-info" role="alert" aria-live="assertive"><i class="fa fa-info-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>
<p class="callout callout-info callout-box" role="alert" aria-live="assertive"><i class="fa fa-info-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>

<p class="callout callout-success" role="alert" aria-live="assertive"><i class="fa fa-check-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>
<p class="callout callout-success callout-box" role="alert" aria-live="assertive"><i class="fa fa-check-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>

<p class="callout callout-warning" role="alert" aria-live="assertive"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>
<p class="callout callout-warning callout-box" role="alert" aria-live="assertive"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>

<p class="callout callout-danger" role="alert" aria-live="assertive"><i class="fa fa-times-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>
<p class="callout callout-danger callout-box" role="alert" aria-live="assertive"><i class="fa fa-times-circle" aria-hidden="true"></i> Li lingues differe solmen in li <code>grammatica</code>, li <code>pronunciation</code> e li plu commun vocabules. Li lingues differe solmen in li grammatica, li <a href="#">pronunciation</a> e li plu commun vocabules.</p>
```
