### ISSUE TITLE
Default list styles

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#73]
```css
ul, ol, dl { margin: 20px 0; }
ul, ol { padding: 0 0 0 40px; }
dl dt {
	font-weight: bold;
	text-transform: uppercase;
	letter-spacing: .05em;
	word-spacing: .15em;
	line-height: 20px;
	margin: 0 0 5px;
}
dl dd {
	line-height: 18px;
	margin: 0 0 10px;
	padding: 0 0 0 10px;
}
dl > :first-child { margin-top: 0 !important; }
dl > :last-child { margin-bottom: 0 !important; }
```

**Comment by mhulse** [comment]
Maybe better?

```css
ul, ol, dl {
	margin: 2rem 0;
	line-height: 1.1;
}
ul, ol { padding: 0 0 0 4rem; }
ul ul, ul ol, ul dl,
ol ol, ol ul, ol dl,
dl dl, dl ul, dl ol { margin: 0; }
dd { margin-left: 2rem; }
dt { font-weight: bold; }
li, dt, dd { margin-bottom: .5rem; }
dd + dt { margin-top: 1rem; }
li > :first-child,
dd > :first-child { margin-top: 0 !important; }
li > :last-child,
dd > :last-child { margin-bottom: 0 !important; }
```
