### ISSUE TITLE
Flex split

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#75]
```css
[eta~="split"] {
	margin: -1rem 0 0 -1rem;
	display: flex;
	flex-direction: row;
	flex-wrap: wrap;
	justify-content: space-between;
	overflow: hidden;
}
[eta~="split"] > * { margin: 1rem 0 0 1rem; }
```

```html
<div eta="split">
	<a eta="button" href="#" onclick="return false;">Link</a>
	<a eta="button disabled" href="#" onclick="return false;">Disabled</a>
	<button eta="button" type="button" name="" onclick="return false;">Button</button>
	<button eta="button" type="submit" name="" onclick="return false;">Reset</button>
</div>
```

Here's what it looks like:

![screenshot 2016-07-11 16 02 31](https://cloud.githubusercontent.com/assets/218624/16749692/ebcf5026-4780-11e6-882d-eb9c7902c688.png)

**Comment by mhulse** [comment]
Responsive version:

```css
[eta~="split"] {
	margin: -1rem 0 0 -1rem;
	display: flex;
	flex: 1 0 auto;
	flex-direction: column;
	flex-wrap: wrap;
	justify-content: space-between;
	overflow: hidden;
}
[eta~="split"] > * {
	margin: 1rem 0 0 1rem;
	flex-grow: 1;
}
@media (min-width: 48rem) {
	[eta~="split"] { flex-direction: row; }
	[eta~="split"] > * { flex-grow: 0; }
}
```
