### ISSUE TITLE
Timer box

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#76]
```html
<p eta="waiting">
	<i class="fa fa-2x fa-clock-o" aria-hidden="true"></i>
	<span>Waiting to begin …</span>
</p>
```

```css
/* http://stackoverflow.com/a/28254903/922323 */
[eta~="waiting"] {
	color: #0f0077;
	border: .2rem solid #0f0077;
	line-height: 1;
	margin: 0;
	padding: 0;
	background: #e9e8f3;
	border-radius: .5rem;
	display: inline-flex;
	flex-direction: row;
	align-items: center;
}
[eta~="waiting"] > * { padding: .5rem 1rem; }
[eta~="waiting"] > :first-child {
	color: #fff;
	background: #0f0077;
	display: flex;
	align-self: stretch;
	align-items: center;
}
```

![screenshot 2016-07-11 16 55 44](https://cloud.githubusercontent.com/assets/218624/16750688/5b325402-4788-11e6-9569-6969d2e82386.png)
