### ISSUE TITLE
Arrows

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#77]
```css
/*
https://css-tricks.com/snippets/css/css-triangle/
For an equilateral triangle it’s worth pointing out that the height is 86.6% of the width so:
(border-left-width + border-right-width) * 0.866% = border-bottom-width
*/

[eta~="arrow"] {
	color: #000;
	border-width: .5rem;
	border-style: solid;
	border-color: transparent;
	line-height: 0;
	width: 0;
	height: 0;
	display: inline-block;
}
[eta~="arrow"][eta~="N"] { border-bottom-color: inherit; }
[eta~="arrow"][eta~="S"] { border-top-color: inherit; }
[eta~="arrow"][eta~="E"] { border-left-color: inherit; }
[eta~="arrow"][eta~="W"] { border-right-color: inherit; }
[eta~="arrow"][eta~="cancel"] { color: #ef3e33; }
[eta~="arrow"][eta~="success"] { color: #5cb85c; }
[eta~="arrow"][eta~="warning"] { color: #efd733; }
```

```html
<span eta="arrow N" aria-hidden="true"></span>,
<span eta="arrow S cancel" aria-hidden="true"></span>,
<span eta="arrow E warning" aria-hidden="true"></span>,
<span eta="arrow W success" aria-hidden="true"></span>,
```

![screenshot 2016-07-13 14 53 52](https://cloud.githubusercontent.com/assets/218624/16821158/a36e8c54-4909-11e6-93cd-b96538c25644.png)
