### ISSUE TITLE
Ear

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#78]
```css
[eta~="flag"] { position: relative; }
[eta~="flag"]::after {
	content: '';
	color: #ef3e33;
	border-width: .65rem;
	border-style: solid;
	border-color: transparent;
	border-right-color: inherit;
	line-height: 0;
	width: 0;
	height: 0;
	position: absolute;
	top: -.5rem;
	left: -.5rem;
	transform: rotate(45deg);
}
```

```html
<li eta="flag"><a href="#">9</a></li>
```

![screenshot 2016-07-13 14 54 49](https://cloud.githubusercontent.com/assets/218624/16821173/c3f9d60e-4909-11e6-8377-68e0a566b664.png)
