### ISSUE TITLE
Make something blink

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#79]
```css
@keyframes blink { 80% { visibility: hidden; } }
[eta="blink"] {
	animation-duration: 2s;
	animation-name: blink;
	animation-iteration-count: infinite;
	animation-timing-function: steps(2, start);
}
```

Like the colon between hours and minutes:

```html
<p eta="tictoc alert">
	<span>48<span eta="blink">:</span>22</span>
	<span>Time remaining</span>
</p>
```
