### ISSUE TITLE
Overflow html/body auto

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#83]
This makes the scroll bar appear when needed:

```css
html,
body { overflow-x: hidden; }
html { overflow-y: auto; }
```

May want to note this in the README.
