### ISSUE TITLE
Flexbox items in a line, with one element taking up leftover space

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#91]
```css
/*
http://justindavis.co/2015/07/13/easy-list-items-with-flexbox/
<div ft-liner>
	<any><any ft-liner="fill">... fills leftover space ...</span><any>
</div>
*/

[ft-liner=""],
[ft-liner=""] > * {
	display: -webkit-flex;
	display: -khtml-flex;
	display: -moz-flex;
	display: -ms-flex;
	display: -o-flex;
	display: flex;
	-webkit-box-align: center;
	   -ms-flex-align: center;
	      align-items: center;
}
[ft-liner=""] > [ft-liner="fill"] {
	-webkit-flex: 1 0 auto;
	 -khtml-flex: 1 0 auto;
	   -moz-flex: 1 0 auto;
	    -ms-flex: 1 0 auto;
	     -o-flex: 1 0 auto;
	        flex: 1 0 auto;
	margin-left: 10px;
}
```
