### ISSUE TITLE
Ellipsis

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#93]
```css
/*
<span person="name" ellipsis>Really Long Name Goes Here</span>
*/

[ellipsis] {
	display: block;
	overflow: hidden;
	white-space: nowrap;
	text-overflow: ellipsis;
}

/*
<span person="name" ellipsis="Really Long Name"></span>
*/

[ellipsis] {
	display: table;
	table-layout: fixed;
	width: 100%;
	white-space: nowrap;
}
[ellipsis]::after {
	content: attr(ellipsis);
	display: table-cell;
	overflow: hidden;
	text-overflow: ellipsis;
}

[ft-off] {
	border: 0;
	clip: rect(0 0 0 0);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute;
	width: 1px;
}
```

http://collaboradev.com/2015/03/28/responsive-css-truncate-and-ellipsis/
