### ISSUE TITLE
Better Helvetica

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#94]
```css
body {
   font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
   font-weight: 300;
}
```

https://css-tricks.com/snippets/css/better-helvetica/
