### ISSUE TITLE
Crosshairs with CSS

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#96]
```css
#crosshairs {
	width: 20px;
	height: 20px;
	position: absolute;
	top: 50%;
	left: 50%;
	-webkit-transform: translate(-50%, -50%);
	   -moz-transform: translate(-50%, -50%);
	    -ms-transform: translate(-50%, -50%);
	     -o-transform: translate(-50%, -50%);
	        transform: translate(-50%, -50%);
	z-index: 100;
	pointer-events: none;
}
#crosshairs::before,
#crosshairs::after {
	content: '';
	width: 2px;
	height: 2px;
	background: rgba(0, 0, 0, .25);
	position: absolute;
}
#crosshairs::before {
	width: 100%;
	top: 50%;
	-webkit-transform: translateY(-50%);
	   -moz-transform: translateY(-50%);
	    -ms-transform: translateY(-50%);
	     -o-transform: translateY(-50%);
	        transform: translateY(-50%);
}
#crosshairs::after {
	height: 100%;
	left: 50%;
	-webkit-transform: translateX(-50%);
	   -moz-transform: translateX(-50%);
	    -ms-transform: translateX(-50%);
	     -o-transform: translateX(-50%);
	        transform: translateX(-50%);
}
```
