### ISSUE TITLE
Disable selection

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#97]
```css
[ft-select="off"] {
	cursor: default;
	-webkit-touch-callout: none;
	-webkit-tap-highlight-color: rgba(0, 0, 0, 0);
	-webkit-tap-highlight-color: transparent;
	-webkit-user-select: none;
	 -khtml-user-select: none;
	   -moz-user-select: none;
	    -ms-user-select: none;
 	     -o-user-select: none;
	        user-select: none;
}
[ft-select="off"] ::-moz-selection { background: transparent; }
[ft-select="off"] ::selection { background: transparent; }
```
