### ISSUE TITLE
Fontawesome Plus and minus for accordion-like headings

### ISSUE THREAD

**Issue by mhulse** [mhulse/css-bullets#98]
```css
.show-more-group .show-more {
	font-size: 16px;
	font-weight: normal;
	color: #3b7097;
	line-height: 1;
	border: 1px solid #ccc;
	cursor: pointer;
	cursor: hand;
	margin: 0;
	padding: 10px 30px 10px 10px;
	position: relative;
}
.show-more-group .show-more::after {
	content: '\f067';
    font-family: FontAwesome;
    font-style: normal;
    font-weight: normal;
    line-height: 1;
    position: absolute;
	top: 50%;
    -webkit-transform: translateY(-50%);
       -moz-transform: translateY(-50%);
        -ms-transform: translateY(-50%);
         -o-transform: translateY(-50%);
            transform: translateY(-50%);
	right: 10px;
}
.show-more-group .show-more.sm-open::after { content: '\f068' }
```
